### ISSUE TITLE
Deployment to collectd.org has broken Go package retrieval

### ISSUE THREAD

**Issue by jefchien** [collectd/collectd.github.io#3]
The Go package for collectd (https://github.com/collectd/go-collectd) expects import paths to begin with [collectd.org](https://www.collectd.org) as seen in the files and in the [installation section](https://github.com/collectd/go-collectd#install) of the README.

Go fetches the package by making a call to the import path with `?go-get=1` (See https://pkg.go.dev/cmd/go#hdr-Remote_import_paths). At each of these paths, it looks for a meta tag in the format of `<meta name="go-import" content="import-prefix vcs repo-root">` and uses that to determine how to clone the package.

This used to work with the previous site, but no longer works with the new GitHub pages based one.

```sh
> go get collectd.org
go: unrecognized import path "collectd.org": parse https://collectd.org/?go-get=1: no go-import meta tags ()

> go get collectd.org/api
go: unrecognized import path "collectd.org/api": reading https://collectd.org/api?go-get=1: 404 Not Found
```

**Comment by octo** [comment]
Fixed by f857b5177a18d689942cadd1c0b53533f09b014e
